### ISSUE TITLE
[INITIAL] django project

### ISSUE THREAD

**Issue by hea9549** [Moong-glE/my-community-backend#11]
django proejct setting하기.

python version 3.7
Django==3.0.3
djangorestframework==3.11.0

에 맞춰서 진행하면 좋을듯합니다.

**Comment by hea9549** [comment]
+ 추가테스크로 해당설정후 requirement.txt 작성해봄 괜찮을듯

**Comment by jhcheon1000** [comment]
requirement.txt에 대한 내용이 어떤 것에 대한 요구사항을 말하는 건가요??

+++
이해했습니다. 감사함당.

**Comment by hea9549** [comment]
아마 찾아봤을거 같은데, 가상환경 관련이야기입니다~!

여러 라이브러리 종속성 관리하는방법이 잇겠지만 pip freeze하는 방식으로 하려합니다

pip으로 `pip freeze > 파일명.txt` 하면 설치된 라이브러리 종속성들이 파일명.txt에 기록되고

다른 환경에서 pip install -r 파일명.txt 하면 고대로 설치댐니다~
