### ISSUE TITLE
[SETTING] settings.py 설정값 분리하기

### ISSUE THREAD

**Issue by hihiboss** [Moong-glE/my-community-backend#14]
## Please Describe The Problem To Be Solved**
- `SECRET_KEY` 노출
- 환경별 설정값 분리 필요
- DB 설정 분리 필요
- STATIC URL 분리 필요
- CORS WHITELIST 분리 필요

## (Optional): Suggest A Solution**
- 각 환경별 세팅 파일을 만들어 분리
- 중요 설정 값은 `.gitignore`를 통해 버전 관리 트래킹을 무시하고 안전한 채널을 통해 공유 및 배포

## REFERENCE
#13

**Comment by hihiboss** [comment]
develop(개발서버용) / test(테스트용) / local(로컬작업용) / production(프로덕트서버용)

**Comment by RyuJaesang** [comment]
개발환경 모두 세팅하고 #29 도 해결했으면 좋겠습니다:)
