### ISSUE TITLE
[DB] Choose the database

### ISSUE THREAD

**Issue by hihiboss** [Moong-glE/my-community-backend#17]
## Please Describe The Problem To Be Solved**
It seems to be not good to use the sqlite 3 for production database.
So, we should choose the database for production.

## (Optional): Suggest A Solution**
RDB
- MySQL
- PostgreSQL

NoSQL
- MongoDB

Please suggest any idea!

**Comment by hihiboss** [comment]
MongoDB

**Comment by hea9549** [comment]
Postrgresql

**Comment by hihiboss** [comment]
with ORM

**Comment by RyuJaesang** [comment]
이슈 닫아주세요~!

**Comment by hihiboss** [comment]
@RyuJaesang 

아직 DB 설정을 한 게 아니라 열어둬야 할 것 같습니다~

**Comment by RyuJaesang** [comment]
알겠슴다~
