### ISSUE TITLE
[Bug] Pull Request template is not applied

### ISSUE THREAD

**Issue by hihiboss** [Moong-glE/my-community-backend#25]
## Symptom
Pull Request template is not applied.
I know that PR template could be only one.

## Solution
Combine but-template and feature-template.
It should have only one template named `PULL_REQUEST_TEMPLATE.md`.
(I'm not sure, but I know that it should be in `.github/` having name `PULL_REQUEST_TEMPLATE.md`.)

**Comment by RyuJaesang** [comment]
옥희독희쓰~!
