### ISSUE TITLE
[MCIP 7] 게시판 권한 부여 여부 논의

### ISSUE THREAD

**Issue by pingoo33** [Moong-glE/my-community-backend#26]
## Please Describe The Problem To Be Solved**

과 및 모임에서 특정 회원에게 게시판 권한 부여 여부에 대한 논의 필요

**Comment by GunHee5719** [comment]
과 관리자의 기능이

1. 과 보드 관리
2. 모임관리자 관리
3. 모임의 생성 및 삭제 (모임 관리)
4. 과 유저 관리

이렇게 4개로 나뉘는 것 같은데, 2,3,4번의 경우 다수의 인원이 권한을 가지면 프로그램 내부 논란을 일으킬 수 있다 생각해서, 2,3,4번은 유일한 관리자 1명 (과 관리자)이 관리하는 것이 맞는 것 같습니다.

다만 1번의 경우 예를 들어 "공지 게시판" 과 같은 경우 과 관리자 1명만이 작성 권한을 가지는 게시판으로 이용하는 것은 너무 기능적 제한이 생기는 부분인 것 같고, 그렇다고 별도의 권한체계를 두는 것은 프로그래밍적 복잡도가 너무 높아지는 것 같아서, 논의가 필요할 것 같습니다.

따라서 

1) 1번 (과 보드 관리) 에 대한 관리 권한 자체를 여러 명 가질 수 있도록 하는 안
2) 1번 내부의 각 게시판 별 관리 권한을 개별적으로 가지도록 하는 안 (root로는 과 관리자가 존재)

에 대해 논의를 해보는 것은 어떨까요?

@als95 @RyuJaesang @hihiboss @jhcheon1000 @hea9549

**Comment by hihiboss** [comment]
@GunHee5719 

제안해주신 
```suggestion
1. 1번 (과 보드 관리) 에 대한 관리 권한 자체를 여러 명 가질 수 있도록 하는 안
2. 1번 내부의 각 게시판 별 관리 권한을 개별적으로 가지도록 하는 안 (root로는 과 관리자가 존재)
```
들은 결국 과 관리자 권한(1,2,3,4)을 1과 2,3,4로 분리하는 것 아닌가요?
과 권리자 권한을 분리하는 것이라면 1,2안 모두 권한 체계를 추가하는 것으로 이해됩니다.
이에 대해서 저희 기능 명세가 커지는 것 같아 저는 부정적인 의견입니다.

그래서 저는 과 관리자 권한을 여러 명으로 설정하는 것으로 해결할 수 있다고 생각합니다.
과 관리자가 여러 명이 되는 것(2,3,4번에 다수가 권한을 가지는 것)이 초래하는 프로그램 내부 논란을 일으킬 것 같다고 하셨는데 여기엔 어떤 것들이 있을지 설명해주시면 감사하겠습니다.

--
위와 별개로 과 보드 관리에 대한 권한을 여러 명이 가질 필요가 있는지에 의문이 들기도 합니다.
게시판 생성과 삭제는 빈번하지 않은 일이고 게시글 혹은 댓글에 대한 삭제는 건의하기나 신고하기 기능 추가로도 가능하여 보드 관리 권한이 여럿일 필요는 없다고 생각합니다.

**Comment by GunHee5719** [comment]
@hihiboss 

지금까지 명세에서 다루지 않은 부분이라는 생각이 드는데, 이 Issue에서 제가 생각했던 "보드 관리 권한" 은 특정 게시판에서의 글쓰기 및 글 삭제 권한이었습니다. 예를 들어 공지게시판과 같은 경우 과 단위로 생각하면 특정 행사 관리자, 혹은 총무와 같은 역할을 담당하는 이용자도 작성 권한이 있어야 한다고 생각해서, 과 관리자 1명만이 작성 권한을 가지는 게시판은 이용에 불편함이 있을 것 같다는 생각입니다.

과 관리자 권한이 여럿이 되는 경우는, 모임의 생성 및 삭제와 같은 권한은 동문네트워크 개발 시 "모임의 삭제"는 심지어 모임 관리자조차도 못하게끔 해두었을 정도로, 중요한 사안이라 여겼습니다. 모임관리자의 관리 또한 마찬가지입니다. 헌데 이에 대한 권한 보유자가 여러명이 되면, 물론 이는 본 앱의 이용자가 관리해야 할 부분이긴 합니다만, 저희 과에 대입해 봤을 때 별로 추천하고 싶지는 않은 제도라 생각합니다.

따라서 저는 관리자 권한을 여럿에게 부여하는 것은 부정적입니다. 헌데 위에서 언급하였듯 "과 보드 관리" 기능 중 하나를 분리해야 할 것 같습니다. 이건 좀 나중에 논의해 봐야 할 사항인 것 같은데, "특정 참여자만 작성할 수 있는 게시판" 이라는 게시판 옵션이 필요할 것 같습니다. (익명여부 선택에 더하여, 작성 권한을 특정 사용자에게 부여하는 옵션)

위 옵션을 추가할 수 있도록 된다면, 별도의 관리 권한을 가지는 것은 필요 없을 것 같습니다. 말씀하신대로 삭제는 신고하기 기능으로 관리가 가능할 것 같습니다.

**Comment by hihiboss** [comment]
@GunHee5719 

말씀 이해했습니다. 감사합니다~!
회의에서 같이 논의해봐야 할 사항이 많네요.

더불어 저희 서비스 컨셉을 Simple로 갈지 Custom으로 갈지도 생각해봐야 할 것 같습니다.
이 컨셉 따라 쉽게 결정될 사항들이 많아보여서요 :)

**Comment by GunHee5719** [comment]
@hihiboss 

넵 게시판 상세 기능 정의 관련해서도 좀 더 얘기 나눠봅시다! 기능+특징 느낌으로

@als95 @hea9549 @RyuJaesang @jhcheon1000
