### ISSUE TITLE
[MCIP 8] 용어 정리

### ISSUE THREAD

**Issue by hihiboss** [Moong-glE/my-community-backend#28]
## Please Describe The Problem To Be Solved**
같은 의미로 여러 가지 용어들이 사용되는 것 같아 용어 정리가 필요하다고 생각합니다.

### 일반 사용자 vs 과 사용자 vs 과 참여자
기존 문서와 회의 때는 `일반 사용자`라고 표현했던 것을 의미합니다.
즉, 과에 가입된 회원을 말합니다.

그러나 만약 과가 삭제될 경우, 과에 가입되지 않은 유령 회원(?)들을 가리킬 필요가 있어 해당 용어에 대한 정리를 제안합니다.

저는 과에 가입되지 않은 my-community 서비스 회원을 `일반 사용자`, 과에 가입된 사용자를 `과 사용자` 라고 하면 어떨지 제안합니다.

추가로 @als95 이 올려준 non functional spec 문서에는 `참여자` 라는 단어가 등장하여 적어둡니다.

### 모임 사용자 vs 모임 참여자
@als95 이 올려준 non functional spec 문서에서 `모임 참여자`라고 표현한 것을 의미합니다.
즉, 모임에 가입된 회원을 말합니다.

이에 대해 사용자와 참여자 중 어떤 용어를 사용할지에 대해 의논 부탁드립니다.

### 게시판 vs 보드
우리는 이전에 사용하던 보드라는 용어가 게시판과 동일한 의미를 가지기로 합의하였습니다.
그럼 과연 이를 게시판으로 부를 것인가 보드로 부를 것인가에 대한 의논이 필요해보입니다.

**Comment by RyuJaesang** [comment]
![image](https://user-images.githubusercontent.com/28643516/86985084-464a0780-c1cb-11ea-8da6-fb9eeca74bcf.png)
이렇게 용어가 정리된다고 생각했는데
모임 참여자 또한 일반 사용자의 범주에 속하게 되고, 이를 구분하는 건 오히려 혼란만 야기할 것 같습니다:)

**Comment by als95** [comment]
### 모임 "관리" vs 과 "관리"

**"관리"**라는 것이 (모임의 삭제 생성과 게시판 관리 등) 어느 범주까지 포함하고 있는지 
모든 문서에서 통일성 있게 사용되어야 할 것 같아

**Comment by hihiboss** [comment]
@RyuJaesang 

앱 관리자는 명시적으로 두지 않아서 용어에서는 빼는게 낫다고 봅니다. (앱 관리자 = 개발자)

과 관리자, 모임 관리자도 결국엔 일반 사용자 범주에 속하지 않나요?!
그리고 '가입한 모임의 게시판을 이용할 수 있다' 혹은 '모임에 가입한 일반 사용자'를 표현하기 위해선 모임참여자 라는 용어를 구분할 필요가 있다고 생각합니다!
실제로 그림(#23, #27)을 그리기 위해서 필연적으로 표현할 수밖에 없기도 하고요 :)

의논해 봅시다~!

**Comment by RyuJaesang** [comment]
#23을 보니
기본적으로 모두 일반 사용자
그리고 이들을 과, 모임의 그룹에 따라 구분해야할 경우 과 참여자, 모임 참여자라고 부르는게 좋을 것 같습니다
또한 보드와 게시판에 대해서는 뭐가 좋을지 잘 모르겠네요😢
@GunHee5719 @als95 @jhcheon1000 @hea9549  의견 부탁드려요~!

**Comment by GunHee5719** [comment]
1. "모임 사용자"보단 "모임 참여자"가 나을 것 같고,
2. "보드" 보다는 "게시판" 이 명확할 것 같습니다.

모임 참여자로 정의하다보니, 과 참여자가 좀 더 통일된 느낌을 줄 것 같습니다.

**Comment by jhcheon1000** [comment]
my-community 서비스 회원 : `일반 사용자`
특정 과에 가입된 `일반 사용자` : `과 참여자`
특정 모임에 가입된 `과 참여자` : `모임 참여자`

이전의 의논들을 종합하면 위와 같은 느낌일까요?

**Comment by hihiboss** [comment]
@jhcheon1000 

네 그렇게 정리될 것 같습니다~!
