### ISSUE TITLE
[Feature Request] Run script 정리

### ISSUE THREAD

**Issue by RyuJaesang** [Moong-glE/my-community-backend#29]
## Please Describe The Problem To Be Solved**
Test script와 Run script를 정리하고 readme에 문서화했으면 좋겠습니다.

**Comment by hihiboss** [comment]
@RyuJaesang 

Test script가 별도로 필요한 이유가 있을까요??
#24 설정대로 가면 `pytest` 명령어만 수행하면 `pytest.ini` 내에 설정된 것들로 테스트를 수행하기에 스크립트 파일은 필요없어보입니다~

--
Run script는 배포 환경 정할 때 변경될 것 같지만 지금 작성해도 나쁘지 않을 것 같습니다~

**Comment by RyuJaesang** [comment]
여기 이슈위에서 처리해도 괜찮을 것 같습니다.
Test Script : python manage.py pytest
Run Script : TODO

로 의논 시작해볼까요?

**Comment by hihiboss** [comment]
@RyuJaesang 

Test script는 위 댓글처럼 생각해서 필요 없을 것 같다고 생각합니다.
혹시 필요한 이유가 있을까요?

Run script는 지금 상황에서 `python manage.py runserver` 정도겠네요.

나중에 애플리케이션이나 DB를 docker로 실행한다면 docker-compose 등으로 묶어버릴 수 있을 것 같습니다.

**Comment by RyuJaesang** [comment]
@hihiboss 

단순히 정리를 위해서 필요하다고 생각했습니다~
필요 없다고 생각하시면 제거하셔도 됩니다~
