### ISSUE TITLE
[Setting] Application 구분

### ISSUE THREAD

**Issue by GunHee5719** [Moong-glE/my-community-backend#37]

**Comment by hihiboss** [comment]
@hea9549's comment in #35 
> 그게 약간 MSA 느낌으로 가는건데 (각 어플리케이션 빼는거)
> 
> 컨벤션이라기보단, 정하기나름! 둘다 쓰는케이스있어요
> 
> 그런데 지금 각 모델의 서비스가 크지않을 것 같아
> 소규모, 처음시작은 models로 모는게 편하고 배우는데 나을듯해서 이렇게가재했엇어욤
> 
> 나중에 기회되면 리팩하고, 지금은 models로 모는걸로 갑시다~
