### ISSUE TITLE
[MC] Impl Model

### ISSUE THREAD

**Issue by GunHee5719** [Moong-glE/my-community-backend#38]
From [Models](https://github.com/Moong-glE/my-community-backend/blob/develop/docs/Database_specification.md),

1-3 : @GunHee5719 
4-6 : @als95 
7,8 : @RyuJaesang 
9,10 : @jhcheon1000 
11,12 : @hihiboss 

please implement basic model

**Comment by RyuJaesang** [comment]
방가방가
