### ISSUE TITLE
[Feature Request] Reduce Verbose Name

### ISSUE THREAD

**Issue by RyuJaesang** [Moong-glE/my-community-backend#48]
How about reducing 'verbose_name' ?
Several merged models are already using long verbose_name.
But for develop convinient and integrety of verbose_name, I suggest changing verbose_name with ONLY ESSENTIAL words.

**Comment by jhcheon1000** [comment]
[verbose_name in django doc](https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.Field.verbose_name)

documentation을 확인하면 verbose_name의 정의가 ___A human-readable name for the field___ 입니다.

따라서 굳이 줄여야할까 라는 의문이 드네요.
