### ISSUE TITLE
[GITHUB] pull request template

### ISSUE THREAD

**Issue by hea9549** [Moong-glE/my-community-backend#5]
- [GITHUB] pull request template 작성
- contribution guide 작성

**Comment by RyuJaesang** [comment]
이건 내가 예전에 썼던 컨트리뷰션 가이드 써볼?

**Comment by hea9549** [comment]
@RyuJaesang  작업 걸고 이 이슈 링크걸어서 풀리퀘 ㄱ ㄱ
